# @link https://docs.gitlab.com/ee/ci/yaml/README.html

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

.build common:
  image: daocloud.io/library/node:9.10.0
  stage: build
  variables:
    BUILD_TEST_FLAG: ''
    BUILD_RELEASE_PATH: docker/dist
  script:
    - npm set registry https://registry.npm.taobao.org
    - yarn
    - yarn run build$BUILD_TEST_FLAG
  artifacts:
    expire_in: 1 week
    paths:
      - $BUILD_RELEASE_PATH

build dev:
  extends: .build common
  variables:
    BUILD_TEST_FLAG: '' # :test
  only:
    - /-test/
  except:
    - branches

build prod:
  extends: .build common
  only:
    - tags
  except:
    - /-test/

# @link https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
.relase common:
  stage: deploy
  image: docker:stable
  retry: 2
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_IMAGE_NAME: $DOCKER_IMAGE
    DOCKER_IMAGE_VERSION: $CI_COMMIT_TAG
    DOCKER_FILE_PATH: ./docker
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_SREVER
  script:
    - docker pull $DOCKER_IMAGE_NAME:latest || true
    - docker build --cache-from $DOCKER_IMAGE_NAME:latest -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION -t $DOCKER_IMAGE_NAME:latest $DOCKER_FILE_PATH
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION
    - docker push $DOCKER_IMAGE_NAME:latest

release dev:
  extends: .relase common
  variables:
    DOCKER_IMAGE_NAME: $DOCKER_IMAGE-test
  only:
    - /-test/
  except:
    - branches

release prod:
  extends: .relase common
  only:
    - tags
  except:
    - /-test/
